name=ESP32-Camera
version=0.0.1
author=Luis Miguel Hernández Samaniego
maintainer=Luis Hernández <louis.miguel.h.s@gmail.com>
sentence=Una biblioteca para controlar una camara OV2640 con el Módulo ESP32 WROVER-E
paragraph=Esta biblioteca permite controlar una camara OV2640 con el Módulo ESP32 WROVER-E de forma facil y sencillo.
category=Communication
url= https://www.luismiguelhs.com/
architectures=ESP32
includes=OV2640.h
depends=*
